version: 2
updates:

  # Set update schedule for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every day
      interval: "daily"

  # Set update schedule for Maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"

  # Set update schedule for Terraform
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      # Check for updates to Terraform every month
      interval: "monthly"
