name: Label deployment trigger

#
# A workflow that will respond to particular labels being added to a Pull Request to create an
# integration environment.
#

on:
  pull_request:
    types:
      - labeled

# TODO may need to gate deployments on PRs from dependabot due to the head reference being illegal as it contains '/'s

jobs:
  deployment:
    name: Create deployment
    runs-on: ubuntu-20.04
    if: |
      github.event.label.name == 'deploy to test' ||
      github.event.label.name == 'deploy to staging' ||
      github.event.label.name == 'deploy to qa'

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Acknowledge Request Label from Pull Request
        id: acknowledge_label
        uses: actions/github-script@v4.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const scriptPath = require('path').resolve('./.github/workflows/scripts/deploymentLabel.js');
            const DeploymentLabel = require(scriptPath);

            const deploymentLabel = new DeploymentLabel(context, core, github);
            await deploymentLabel.acknowledgeDeployLabel();


      - name: Get temporary token for creating deployment
        id: temp_token
        uses: peter-murray/workflow-application-token-action@v1.0.3
        with:
          application_id: ${{ secrets.OCTODEMOBOT_APPLICATION_ID_REPO_AUTOMATION }}
          application_private_key: ${{ secrets.OCTODEMOBOT_APPLICATION_KEY_REPO_AUTOMATION }}

      - name: Create Deployment
        uses: actions/github-script@v4.0.2
        env:
          container_registry: ghcr.io
          app_container_image: ${{ github.repository_owner }}/${{ steps.acknowledge_label.outputs.app_container_image }}
          app_container_version: ${{ steps.acknowledge_label.outputs.app_container_version }}

        with:
          github-token: ${{ steps.temp_token.outputs.token }}
          script: |
            const scriptPath = require('path').resolve('./.github/workflows/scripts/createDeployment.js');
            const createDeployment = require(scriptPath);

            const LABEL_TO_ENVIRONMENT = {
              'deploy to qa': 'qa',
              'deploy to staging': 'staging',
              'deploy to test': 'test'
            };

            await createDeployment({
              context: context,
              github: github,
              environment: LABEL_TO_ENVIRONMENT[context.payload.label.name.toLowerCase()],
              containerRegistry: process.env.container_registry,
              appContainerImage: process.env.app_container_image,
              appContainerVersion: process.env.app_container_version,
              sha: context.sha,
              head: context.payload.pull_request.head.ref, //Branch name PR created from
            });

      - name: Report Failure
        if: failure()
        uses: actions/github-script@v4.0.2
        with:
          script: |
            const commentBody = `Failure in _${context.payload.label.name.toLowerCase()}_, for more details see https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${process.env.GITHUB_RUN_ID}`;

            await github.issues.createComment({
              ...context.repo,
              issue_number: context.payload.number,
              body: commentBody,
            });